### ISSUE TITLE
Need ur contact to discuss about future updates

### ISSUE THREAD

**Issue by NatsumeAoii** [lonewolfcoder2007/NewFantasy#1]
send me ur discord or something, so i can communicate about this project

**Comment by lonewolfcoder2007** [comment]
Sure. Username is lonewof2007. Discord, ofc.

**Comment by NatsumeAoii** [comment]
i cant find it, so add me

natsumeaoi

**Comment by lonewolfcoder2007** [comment]
All good. Check the DMs.
